name: dotnet5-newman-containers-acr-appservice

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_AZURECR: ${{ secrets.AZURECR_REGISTRY }}/apitemperatura-newman
  CAMINHO_PROJETO_WEBAPP: ./APITemperatura
  CAMINHO_TESTES: ./Tests

jobs:
  build-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build de imagem
      run: |
        cd ${{ env.CAMINHO_PROJETO_WEBAPP }}
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_AZURECR }}:latest
        
    - name: Testes da API REST com Newman
      run: |
        cd ${{ env.CAMINHO_TESTES }}
        newman run .\ConversaoTemperaturas.postman_collection.json -d .\testes.json
